# Generated by Django 4.2 on 2023-06-17 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('dias_trabajo', models.CharField(max_length=100)),
                ('turno', models.CharField(choices=[('dia', 'Día'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10)),
                ('horario_entrada', models.TimeField()),
                ('horario_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateTimeField()),
                ('tipo_marcacion', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.empleado')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
