# Generated by Django 4.2 on 2023-04-28 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('cant_huespedes', models.SmallIntegerField()),
                ('tipo_habitacion', models.CharField(max_length=5)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(max_length=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.hotel')),
            ],
        ),
    ]
