# Generated by Django 4.2 on 2023-08-04 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField()),
                ('aceptado', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.cancha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.usuario')),
            ],
        ),
    ]
