# Generated by Django 4.2 on 2023-08-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_cancha_usuario_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cancha',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Cancha',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
